name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  path_provider: 
  shared_preferences: 
  permission_handler: 
  flutter:
    sdk: flutter
  workmanager: 

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true