name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  path_provider: ^2.1.5 
  shared_preferences: ^2.3.0
  permission_handler: ^11.3.1 
  flutter:
    sdk: flutter
  workmanager:
  uuid: ^4.4.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true