name: workmanager
description: Flutter Workmanager. This plugin allows you to schedule background work on Android and iOS.
version: 0.2.4
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.4
  get_it: ^5.0.6
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.tramckrijte.workmanager
        pluginClass: WorkmanagerPlugin
      ios:
        pluginClass: WorkmanagerPlugin
