name: workmanager_platform_interface
description: A common platform interface for the workmanager plugin.
version: 0.8.0
# publish_to: none
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0

