name: workmanager
description: Flutter Workmanager. This plugin allows you to schedule background work on Android and iOS.
version: 0.8.0
# publish_to: none
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  workmanager_platform_interface: ^0.8.0
  workmanager_android: ^0.8.0
  workmanager_ios: ^0.8.0

dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.4
  get_it: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: workmanager_android
      ios:
        default_package: workmanager_ios
