name: workmanager
description: Flutter Workmanager. This plugin allows you to schedule background work on Android and iOS.
version: 0.5.2
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  test: ^1.16.3
  mockito: ^5.0.4
  get_it: ^7.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.workmanager
        pluginClass: WorkmanagerPlugin
      ios:
        pluginClass: WorkmanagerPlugin
