name: format + publishable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format_dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Format
        run: |
          dart format --set-exit-if-changed .

  format_kotlin:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}

  format_swift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  publishable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: publish checks
        run: |
          dart pub global activate melos
          melos bootstrap
          cd workmanager
          flutter pub get
          flutter pub publish -n
          flutter pub dart analyze